/********************************************************************
* catcore_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error catcore_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablecatcore_dict();
extern void G__cpp_setup_inheritancecatcore_dict();
extern void G__cpp_setup_typetablecatcore_dict();
extern void G__cpp_setup_memvarcatcore_dict();
extern void G__cpp_setup_globalcatcore_dict();
extern void G__cpp_setup_memfunccatcore_dict();
extern void G__cpp_setup_funccatcore_dict();
extern void G__set_cpp_environmentcatcore_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TArtFadcRawDataObject.h"
#include "TArtDecoderV1740.h"
#include "TArtDecoderSIS3610.h"
#include "TArtDecoderSIS3820.h"
#include "TCatDecoderV1190.h"
#include "TCatRawDataV1190.h"
#include "TArtKbhit.h"
#include "TCatObject.h"
#include "TCatSimpleData.h"
#include "TCatHitV1190.h"
#include "TCatSortable.h"
#include "TCatDetectorArray.h"
#include "TCatHistManager.h"
#include "TCatPadManager.h"
#include "TCatRawDataCategorized.h"
#include "TCatStreamBuf.h"
#include "TCatOstream.h"
#include "TCatObjRefArray.h"
#include "TCatParameter.h"
#include "TCatParameterStrings.h"
#include "TCatTypes.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__catcore_dictLN_TClass;
extern G__linked_taginfo G__catcore_dictLN_TBuffer;
extern G__linked_taginfo G__catcore_dictLN_TMemberInspector;
extern G__linked_taginfo G__catcore_dictLN_TObject;
extern G__linked_taginfo G__catcore_dictLN_TNamed;
extern G__linked_taginfo G__catcore_dictLN_TString;
extern G__linked_taginfo G__catcore_dictLN_ios_base;
extern G__linked_taginfo G__catcore_dictLN_basic_ioslEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__catcore_dictLN_basic_streambuflEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__catcore_dictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__catcore_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__catcore_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__catcore_dictLN_TList;
extern G__linked_taginfo G__catcore_dictLN_TClonesArray;
extern G__linked_taginfo G__catcore_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__catcore_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__catcore_dictLN_TArtRawDataObject;
extern G__linked_taginfo G__catcore_dictLN_TArtFadcRawDataObject;
extern G__linked_taginfo G__catcore_dictLN_TArtRawSegmentObject;
extern G__linked_taginfo G__catcore_dictLN_vectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgR;
extern G__linked_taginfo G__catcore_dictLN_reverse_iteratorlEvectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__catcore_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__catcore_dictLN_TArtDecoder;
extern G__linked_taginfo G__catcore_dictLN_TArtDecoderV1740;
extern G__linked_taginfo G__catcore_dictLN_TArtDecoderSIS3610;
extern G__linked_taginfo G__catcore_dictLN_TArtDecoderSIS3820;
extern G__linked_taginfo G__catcore_dictLN_TCatObject;
extern G__linked_taginfo G__catcore_dictLN_TCatObjectcLcLESortType;
extern G__linked_taginfo G__catcore_dictLN_TCatObjectcLcLESortOrder;
extern G__linked_taginfo G__catcore_dictLN_TCatRawDataV1190;
extern G__linked_taginfo G__catcore_dictLN_TArtKbhit;
extern G__linked_taginfo G__catcore_dictLN_TArtKbhitcLcLtermios;
extern G__linked_taginfo G__catcore_dictLN_TCatSimpleData;
extern G__linked_taginfo G__catcore_dictLN_TCatSimpleDatacLcLESimpleDataSortType;
extern G__linked_taginfo G__catcore_dictLN_TCatHitV1190;
extern G__linked_taginfo G__catcore_dictLN_TCatHitV1190cLcLEStatus;
extern G__linked_taginfo G__catcore_dictLN_TCatSortable;
extern G__linked_taginfo G__catcore_dictLN_TCatDetectorArray;
extern G__linked_taginfo G__catcore_dictLN_TCatHistManager;
extern G__linked_taginfo G__catcore_dictLN_TRefArray;
extern G__linked_taginfo G__catcore_dictLN_TCatObjRefArray;
extern G__linked_taginfo G__catcore_dictLN_TCatRawDataCategorized;
extern G__linked_taginfo G__catcore_dictLN_TCatStreamBuf;
extern G__linked_taginfo G__catcore_dictLN_listlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__catcore_dictLN_TCatOstream;
extern G__linked_taginfo G__catcore_dictLN_TCatOstreamcLcLEBufType_t;
extern G__linked_taginfo G__catcore_dictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__catcore_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__catcore_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__catcore_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__catcore_dictLN_maplETStringcOvectorlETStringcOallocatorlETStringgRsPgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOvectorlETStringcOallocatorlETStringgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__catcore_dictLN_TCatParameter_tlEintgR;
extern G__linked_taginfo G__catcore_dictLN_TCatParameter_tlEfloatgR;
extern G__linked_taginfo G__catcore_dictLN_TCatParameter_tlEvectorlEintcOallocatorlEintgRsPgRsPgR;
extern G__linked_taginfo G__catcore_dictLN_TCatParameter_tlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgR;
extern G__linked_taginfo G__catcore_dictLN_TCatParameter_tlEvectorlETStringcOallocatorlETStringgRsPgRsPgR;

/* STUB derived class for protected member access */
