/********************************************************************
* catmain_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error catmain_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablecatmain_dict();
extern void G__cpp_setup_inheritancecatmain_dict();
extern void G__cpp_setup_typetablecatmain_dict();
extern void G__cpp_setup_memvarcatmain_dict();
extern void G__cpp_setup_globalcatmain_dict();
extern void G__cpp_setup_memfunccatmain_dict();
extern void G__cpp_setup_funccatmain_dict();
extern void G__set_cpp_environmentcatmain_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TArtRint.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__catmain_dictLN_TObject;
extern G__linked_taginfo G__catmain_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__catmain_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__catmain_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__catmain_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__catmain_dictLN_TQObject;
extern G__linked_taginfo G__catmain_dictLN_TApplication;
extern G__linked_taginfo G__catmain_dictLN_TRint;
extern G__linked_taginfo G__catmain_dictLN_TArtRint;

/* STUB derived class for protected member access */
