/********************************************************************
* catcmd_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error catcmd_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablecatcmd_dict();
extern void G__cpp_setup_inheritancecatcmd_dict();
extern void G__cpp_setup_typetablecatcmd_dict();
extern void G__cpp_setup_memvarcatcmd_dict();
extern void G__cpp_setup_globalcatcmd_dict();
extern void G__cpp_setup_memfunccatcmd_dict();
extern void G__cpp_setup_funccatcmd_dict();
extern void G__set_cpp_environmentcatcmd_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TCatCmdFactory.h"
#include "TCatCmd.h"
#include "TCatCmdHt.h"
#include "TCatCmdHtp.h"
#include "TCatCmdHb.h"
#include "TCatCmdHn.h"
#include "TCatCmdZone.h"
#include "TCatCmdPr.h"
#include "TCatCmdPrx.h"
#include "TCatCmdPry.h"
#include "TCatCmdBn.h"
#include "TCatCmdBnx.h"
#include "TCatCmdBny.h"
#include "TCatCmdSl.h"
#include "TCatCmdSly.h"
#include "TCatCmdLs.h"
#include "TCatCmdCd.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__catcmd_dictLN_TClass;
extern G__linked_taginfo G__catcmd_dictLN_TBuffer;
extern G__linked_taginfo G__catcmd_dictLN_TMemberInspector;
extern G__linked_taginfo G__catcmd_dictLN_TObject;
extern G__linked_taginfo G__catcmd_dictLN_TNamed;
extern G__linked_taginfo G__catcmd_dictLN_TString;
extern G__linked_taginfo G__catcmd_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__catcmd_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__catcmd_dictLN_TObjArray;
extern G__linked_taginfo G__catcmd_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__catcmd_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmd;
extern G__linked_taginfo G__catcmd_dictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__catcmd_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdFactory;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdHt;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdHtp;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdHb;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdHn;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdZone;
extern G__linked_taginfo G__catcmd_dictLN_TH1;
extern G__linked_taginfo G__catcmd_dictLN_TH2;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdPr;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdPrcLcLEAxis;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdPrx;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdPry;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdBn;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdBncLcLEAxis;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdBnx;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdBny;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdSl;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdSlcLcLEAxis;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdSly;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdLs;
extern G__linked_taginfo G__catcmd_dictLN_TCatCmdCd;

/* STUB derived class for protected member access */
