//
// File generated by rootcint at Sun Feb  5 11:41:39 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME catuhodo_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "catuhodo_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TCatUHodoPl_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TCatUHodoPl(void *p = 0);
   static void *newArray_TCatUHodoPl(Long_t size, void *p);
   static void delete_TCatUHodoPl(void *p);
   static void deleteArray_TCatUHodoPl(void *p);
   static void destruct_TCatUHodoPl(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TCatUHodoPl*)
   {
      ::TCatUHodoPl *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TCatUHodoPl >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TCatUHodoPl", ::TCatUHodoPl::Class_Version(), "./TCatUHodoPl.h", 16,
                  typeid(::TCatUHodoPl), DefineBehavior(ptr, ptr),
                  &::TCatUHodoPl::Dictionary, isa_proxy, 4,
                  sizeof(::TCatUHodoPl) );
      instance.SetNew(&new_TCatUHodoPl);
      instance.SetNewArray(&newArray_TCatUHodoPl);
      instance.SetDelete(&delete_TCatUHodoPl);
      instance.SetDeleteArray(&deleteArray_TCatUHodoPl);
      instance.SetDestructor(&destruct_TCatUHodoPl);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TCatUHodoPl*)
   {
      return GenerateInitInstanceLocal((::TCatUHodoPl*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TCatUHodoPl*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void TCatUHodo_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TCatUHodo(void *p = 0);
   static void *newArray_TCatUHodo(Long_t size, void *p);
   static void delete_TCatUHodo(void *p);
   static void deleteArray_TCatUHodo(void *p);
   static void destruct_TCatUHodo(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TCatUHodo*)
   {
      ::TCatUHodo *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TCatUHodo >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TCatUHodo", ::TCatUHodo::Class_Version(), "./TCatUHodo.h", 17,
                  typeid(::TCatUHodo), DefineBehavior(ptr, ptr),
                  &::TCatUHodo::Dictionary, isa_proxy, 4,
                  sizeof(::TCatUHodo) );
      instance.SetNew(&new_TCatUHodo);
      instance.SetNewArray(&newArray_TCatUHodo);
      instance.SetDelete(&delete_TCatUHodo);
      instance.SetDeleteArray(&deleteArray_TCatUHodo);
      instance.SetDestructor(&destruct_TCatUHodo);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TCatUHodo*)
   {
      return GenerateInitInstanceLocal((::TCatUHodo*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TCatUHodo*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TCatUHodoPl::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TCatUHodoPl::Class_Name()
{
   return "TCatUHodoPl";
}

//______________________________________________________________________________
const char *TCatUHodoPl::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TCatUHodoPl*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TCatUHodoPl::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TCatUHodoPl*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TCatUHodoPl::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TCatUHodoPl*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TCatUHodoPl::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TCatUHodoPl*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *TCatUHodo::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TCatUHodo::Class_Name()
{
   return "TCatUHodo";
}

//______________________________________________________________________________
const char *TCatUHodo::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TCatUHodo*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TCatUHodo::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TCatUHodo*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TCatUHodo::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TCatUHodo*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TCatUHodo::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TCatUHodo*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TCatUHodoPl::Streamer(TBuffer &R__b)
{
   // Stream an object of class TCatUHodoPl.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(TCatUHodoPl::Class(),this);
   } else {
      R__b.WriteClassBuffer(TCatUHodoPl::Class(),this);
   }
}

//______________________________________________________________________________
void TCatUHodoPl::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TCatUHodoPl.
      TClass *R__cl = ::TCatUHodoPl::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTime", &fTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCharge", &fCharge);
      TCatObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TCatUHodoPl(void *p) {
      return  p ? new(p) ::TCatUHodoPl : new ::TCatUHodoPl;
   }
   static void *newArray_TCatUHodoPl(Long_t nElements, void *p) {
      return p ? new(p) ::TCatUHodoPl[nElements] : new ::TCatUHodoPl[nElements];
   }
   // Wrapper around operator delete
   static void delete_TCatUHodoPl(void *p) {
      delete ((::TCatUHodoPl*)p);
   }
   static void deleteArray_TCatUHodoPl(void *p) {
      delete [] ((::TCatUHodoPl*)p);
   }
   static void destruct_TCatUHodoPl(void *p) {
      typedef ::TCatUHodoPl current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TCatUHodoPl

//______________________________________________________________________________
void TCatUHodo::Streamer(TBuffer &R__b)
{
   // Stream an object of class TCatUHodo.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(TCatUHodo::Class(),this);
   } else {
      R__b.WriteClassBuffer(TCatUHodo::Class(),this);
   }
}

//______________________________________________________________________________
void TCatUHodo::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TCatUHodo.
      TClass *R__cl = ::TCatUHodo::IsA();
      if (R__cl || R__insp.IsA()) { }
      TCatDetectorArray::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TCatUHodo(void *p) {
      return  p ? new(p) ::TCatUHodo : new ::TCatUHodo;
   }
   static void *newArray_TCatUHodo(Long_t nElements, void *p) {
      return p ? new(p) ::TCatUHodo[nElements] : new ::TCatUHodo[nElements];
   }
   // Wrapper around operator delete
   static void delete_TCatUHodo(void *p) {
      delete ((::TCatUHodo*)p);
   }
   static void deleteArray_TCatUHodo(void *p) {
      delete [] ((::TCatUHodo*)p);
   }
   static void destruct_TCatUHodo(void *p) {
      typedef ::TCatUHodo current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TCatUHodo

/********************************************************
* catuhodo_dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablecatuhodo_dict();

extern "C" void G__set_cpp_environmentcatuhodo_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TCatUHodoPl.h");
  G__add_compiledheader("TCatUHodo.h");
  G__cpp_reset_tagtablecatuhodo_dict();
}
#include <new>
extern "C" int G__cpp_dllrevcatuhodo_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TCatUHodoPl */
static int G__catuhodo_dict_178_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TCatUHodoPl* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TCatUHodoPl[n];
     } else {
       p = new((void*) gvp) TCatUHodoPl[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TCatUHodoPl;
     } else {
       p = new((void*) gvp) TCatUHodoPl;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodoPl));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_178_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TCatUHodoPl*) G__getstructoffset())->SetTime(*(Double_t*) G__Doubleref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_178_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TCatUHodoPl*) G__getstructoffset())->SetCharge(*(Double_t*) G__Doubleref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_178_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TCatUHodoPl*) G__getstructoffset())->GetTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_178_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TCatUHodoPl*) G__getstructoffset())->GetCharge());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_178_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TCatUHodoPl::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_178_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TCatUHodoPl::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_178_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TCatUHodoPl::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_178_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TCatUHodoPl::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_178_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TCatUHodoPl*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_178_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TCatUHodoPl::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_178_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TCatUHodoPl::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_178_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TCatUHodoPl::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_178_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TCatUHodoPl::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__catuhodo_dict_178_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TCatUHodoPl* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TCatUHodoPl(*(TCatUHodoPl*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodoPl));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TCatUHodoPl G__TTCatUHodoPl;
static int G__catuhodo_dict_178_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TCatUHodoPl*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TCatUHodoPl*) (soff+(sizeof(TCatUHodoPl)*i)))->~G__TTCatUHodoPl();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TCatUHodoPl*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TCatUHodoPl*) (soff))->~G__TTCatUHodoPl();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__catuhodo_dict_178_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TCatUHodoPl* dest = (TCatUHodoPl*) G__getstructoffset();
   *dest = *(TCatUHodoPl*) libp->para[0].ref;
   const TCatUHodoPl& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TCatUHodo */
static int G__catuhodo_dict_188_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TCatUHodo* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TCatUHodo[n];
     } else {
       p = new((void*) gvp) TCatUHodo[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TCatUHodo;
     } else {
       p = new((void*) gvp) TCatUHodo;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodo));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_188_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TCatUHodo*) G__getstructoffset())->AddHit(*(Int_t*) G__Intref(&libp->para[0]), *(Double_t*) G__Doubleref(&libp->para[1])
, *(Double_t*) G__Doubleref(&libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_188_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TCatUHodo*) G__getstructoffset())->GetHit(*(Int_t*) G__Intref(&libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_188_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TCatUHodo::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_188_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TCatUHodo::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_188_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TCatUHodo::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_188_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TCatUHodo::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_188_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TCatUHodo*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_188_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TCatUHodo::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_188_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TCatUHodo::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_188_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TCatUHodo::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__catuhodo_dict_188_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TCatUHodo::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__catuhodo_dict_188_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TCatUHodo* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TCatUHodo(*(TCatUHodo*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodo));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TCatUHodo G__TTCatUHodo;
static int G__catuhodo_dict_188_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TCatUHodo*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TCatUHodo*) (soff+(sizeof(TCatUHodo)*i)))->~G__TTCatUHodo();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TCatUHodo*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TCatUHodo*) (soff))->~G__TTCatUHodo();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__catuhodo_dict_188_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TCatUHodo* dest = (TCatUHodo*) G__getstructoffset();
   *dest = *(TCatUHodo*) libp->para[0].ref;
   const TCatUHodo& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TCatUHodoPl */

/* TCatUHodo */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunccatuhodo_dict {
 public:
  G__Sizep2memfunccatuhodo_dict(): p(&G__Sizep2memfunccatuhodo_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunccatuhodo_dict::*p)();
};

size_t G__get_sizep2memfunccatuhodo_dict()
{
  G__Sizep2memfunccatuhodo_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancecatuhodo_dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodoPl))) {
     TCatUHodoPl *G__Lderived;
     G__Lderived=(TCatUHodoPl*)0x1000;
     {
       TCatObject *G__Lpbase=(TCatObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodoPl),G__get_linked_tagnum(&G__catuhodo_dictLN_TCatObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodoPl),G__get_linked_tagnum(&G__catuhodo_dictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodoPl),G__get_linked_tagnum(&G__catuhodo_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodo))) {
     TCatUHodo *G__Lderived;
     G__Lderived=(TCatUHodo*)0x1000;
     {
       TCatDetectorArray *G__Lpbase=(TCatDetectorArray*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodo),G__get_linked_tagnum(&G__catuhodo_dictLN_TCatDetectorArray),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TCatObject *G__Lpbase=(TCatObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodo),G__get_linked_tagnum(&G__catuhodo_dictLN_TCatObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodo),G__get_linked_tagnum(&G__catuhodo_dictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodo),G__get_linked_tagnum(&G__catuhodo_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablecatuhodo_dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__catuhodo_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__catuhodo_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__catuhodo_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__catuhodo_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__catuhodo_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__catuhodo_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__catuhodo_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__catuhodo_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__catuhodo_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__catuhodo_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__catuhodo_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__catuhodo_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__catuhodo_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__catuhodo_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TCatUHodoPl */
static void G__setup_memvarTCatUHodoPl(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodoPl));
   { TCatUHodoPl *p; p=(TCatUHodoPl*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fTime=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fCharge=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__catuhodo_dictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TCatUHodo */
static void G__setup_memvarTCatUHodo(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodo));
   { TCatUHodo *p; p=(TCatUHodo*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__catuhodo_dictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarcatuhodo_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTCatUHodoPl(void) {
   /* TCatUHodoPl */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodoPl));
   G__memfunc_setup("TCatUHodoPl",1031,G__catuhodo_dict_178_0_1, 105, G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodoPl), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTime",699,G__catuhodo_dict_178_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 11 - time", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCharge",886,G__catuhodo_dict_178_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 11 - charge", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTime",687,G__catuhodo_dict_178_0_4, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCharge",874,G__catuhodo_dict_178_0_5, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Compare",711,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 8, "U 'TObject' - 10 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("IsSortable",1016,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__catuhodo_dict_178_0_8, 85, G__get_linked_tagnum(&G__catuhodo_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TCatUHodoPl::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__catuhodo_dict_178_0_9, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TCatUHodoPl::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__catuhodo_dict_178_0_10, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TCatUHodoPl::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__catuhodo_dict_178_0_11, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TCatUHodoPl::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__catuhodo_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__catuhodo_dict_178_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__catuhodo_dict_178_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TCatUHodoPl::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__catuhodo_dict_178_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TCatUHodoPl::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__catuhodo_dict_178_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TCatUHodoPl::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__catuhodo_dict_178_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TCatUHodoPl::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TCatUHodoPl", 1031, G__catuhodo_dict_178_0_20, (int) ('i'), G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodoPl), -1, 0, 1, 1, 1, 0, "u 'TCatUHodoPl' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TCatUHodoPl", 1157, G__catuhodo_dict_178_0_21, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__catuhodo_dict_178_0_22, (int) ('u'), G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodoPl), -1, 1, 1, 1, 1, 0, "u 'TCatUHodoPl' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTCatUHodo(void) {
   /* TCatUHodo */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodo));
   G__memfunc_setup("TCatUHodo",843,G__catuhodo_dict_188_0_1, 105, G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodo), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddHit",558,G__catuhodo_dict_188_0_2, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - 'Int_t' 11 - id d - 'Double_t' 11 - time "
"d - 'Double_t' 11 - charge", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetHit",581,G__catuhodo_dict_188_0_4, 85, G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodoPl), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 11 - idx", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__catuhodo_dict_188_0_5, 85, G__get_linked_tagnum(&G__catuhodo_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TCatUHodo::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__catuhodo_dict_188_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TCatUHodo::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__catuhodo_dict_188_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TCatUHodo::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__catuhodo_dict_188_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TCatUHodo::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__catuhodo_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__catuhodo_dict_188_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__catuhodo_dict_188_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TCatUHodo::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__catuhodo_dict_188_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TCatUHodo::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__catuhodo_dict_188_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TCatUHodo::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__catuhodo_dict_188_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TCatUHodo::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TCatUHodo", 843, G__catuhodo_dict_188_0_17, (int) ('i'), G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodo), -1, 0, 1, 1, 1, 0, "u 'TCatUHodo' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TCatUHodo", 969, G__catuhodo_dict_188_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__catuhodo_dict_188_0_19, (int) ('u'), G__get_linked_tagnum(&G__catuhodo_dictLN_TCatUHodo), -1, 1, 1, 1, 1, 0, "u 'TCatUHodo' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunccatuhodo_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalcatuhodo_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funccatuhodo_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__catuhodo_dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__catuhodo_dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__catuhodo_dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__catuhodo_dictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__catuhodo_dictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__catuhodo_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__catuhodo_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__catuhodo_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__catuhodo_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__catuhodo_dictLN_TCatObject = { "TCatObject" , 99 , -1 };
G__linked_taginfo G__catuhodo_dictLN_TCatUHodoPl = { "TCatUHodoPl" , 99 , -1 };
G__linked_taginfo G__catuhodo_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__catuhodo_dictLN_TCatDetectorArray = { "TCatDetectorArray" , 99 , -1 };
G__linked_taginfo G__catuhodo_dictLN_TCatUHodo = { "TCatUHodo" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablecatuhodo_dict() {
  G__catuhodo_dictLN_TClass.tagnum = -1 ;
  G__catuhodo_dictLN_TBuffer.tagnum = -1 ;
  G__catuhodo_dictLN_TMemberInspector.tagnum = -1 ;
  G__catuhodo_dictLN_TObject.tagnum = -1 ;
  G__catuhodo_dictLN_TNamed.tagnum = -1 ;
  G__catuhodo_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__catuhodo_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__catuhodo_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__catuhodo_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__catuhodo_dictLN_TCatObject.tagnum = -1 ;
  G__catuhodo_dictLN_TCatUHodoPl.tagnum = -1 ;
  G__catuhodo_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__catuhodo_dictLN_TCatDetectorArray.tagnum = -1 ;
  G__catuhodo_dictLN_TCatUHodo.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablecatuhodo_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_TObject);
   G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_TCatObject);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_TCatUHodoPl),sizeof(TCatUHodoPl),-1,324864,(char*)NULL,G__setup_memvarTCatUHodoPl,G__setup_memfuncTCatUHodoPl);
   G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_TCatDetectorArray);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__catuhodo_dictLN_TCatUHodo),sizeof(TCatUHodo),-1,324864,(char*)NULL,G__setup_memvarTCatUHodo,G__setup_memfuncTCatUHodo);
}
extern "C" void G__cpp_setupcatuhodo_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupcatuhodo_dict()");
  G__set_cpp_environmentcatuhodo_dict();
  G__cpp_setup_tagtablecatuhodo_dict();

  G__cpp_setup_inheritancecatuhodo_dict();

  G__cpp_setup_typetablecatuhodo_dict();

  G__cpp_setup_memvarcatuhodo_dict();

  G__cpp_setup_memfunccatuhodo_dict();
  G__cpp_setup_globalcatuhodo_dict();
  G__cpp_setup_funccatuhodo_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunccatuhodo_dict();
  return;
}
class G__cpp_setup_initcatuhodo_dict {
  public:
    G__cpp_setup_initcatuhodo_dict() { G__add_setup_func("catuhodo_dict",(G__incsetup)(&G__cpp_setupcatuhodo_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initcatuhodo_dict() { G__remove_setup_func("catuhodo_dict"); }
};
G__cpp_setup_initcatuhodo_dict G__cpp_setup_initializercatuhodo_dict;

